### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hwkns** [rdegges/django-heroku-memcacheify#13]
Does django-heroku-memcacheify support Python 3?

If so, it would be nice to designate that on PyPI using classifiers in setup.py (see https://pypi.python.org/pypi?%3Aaction=list_classifiers)

If not, what does the path forward look like?

**Comment by meshy** [comment]
[Python 3 support has come to `pylibmc`](lericson/pylibmc#146), and there is a [good looking PR on `django-pylibmc`](https://github.com/jbalogh/django-pylibmc/pull/30) too!
Fingers crossed! `:D`

**Comment by rdegges** [comment]
I'm still down to merge this in whenever the dependent libraries are updated! I'd like py3k support as well =)
